use_frameworks!

platform :ios, '9.0'

target 'XSJZjhTestNetworking_Example' do
  pod 'XSJZjhTestNetworking', :path => '../'

  target 'XSJZjhTestNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
